# -*- coding: utf-8 -*-
"""QClab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roHCoZptNCEGCW9y1NNgk0sSXnnJXDnI
"""

!pip install qiskit
import numpy as np
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_histogram

# |0> and |1>
ket0 = np.array([1, 0])
ket1 = np.array([0, 1])

# Example: compute their average state
avg_state = (ket0 + ket1) / np.sqrt(2)
print(avg_state)

# Convert to Statevector objects
sv0 = Statevector(ket0)
sv1 = Statevector(ket1)
sv_avg = Statevector(avg_state)

# Check if they are valid quantum states
print(sv_avg.is_valid())  # Should return True

# Display in text
sv_avg.draw('text')

# Display in LaTeX (requires Jupyter Notebook to render properly)
sv_avg.draw('latex')

# One measurement
result, post_measurement_state = sv_avg.measure()
print("Measurement result:", result)
print("Post-measurement state:", post_measurement_state)

# Measure many times
counts = sv_avg.sample_counts(1000)  # 1000 trials
print(counts)

# Plot the results
plot_histogram(counts)

u = np.array([np.sqrt(5/9), np.sqrt(4/9)])
sv_u = Statevector(u)

# Check validity and sample counts
print(sv_u.is_valid())  # True
counts_u = sv_u.sample_counts(1000)
plot_histogram(counts_u)